# Generated by Django 6.0.1 on 2026-01-18 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text="Permission code in format 'app_label.action_model'", max_length=100)),
                ('name', models.CharField(help_text='Human-readable name for the permission', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of what this permission grants')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the permission was created')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'tenant_authx_permission',
                'ordering': ['tenant', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the tenant', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the tenant', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (must be unique)', max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain for tenant (optional)', max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the tenant is currently active')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom metadata for the tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the tenant was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the tenant was last updated')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenant_authx_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the role', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text="Description of the role's purpose")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the role is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the role was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the role was last updated')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted by this role', related_name='roles', to='tenant_authx.permission')),
                ('tenant', models.ForeignKey(help_text='The tenant this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenant_authx.tenant')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'tenant_authx_role',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this permission belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenant_authx.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is currently active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined the tenant')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the membership was last updated')),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles assigned to this user in this tenant', related_name='memberships', to='tenant_authx.role')),
                ('tenant', models.ForeignKey(help_text='The tenant the user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant_authx.tenant')),
                ('user', models.ForeignKey(help_text='The user who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'db_table': 'tenant_authx_membership',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'name'], name='tenant_auth_tenant__803b69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['tenant', 'codename'], name='tenant_auth_tenant__562913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'codename')},
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'tenant'], name='tenant_auth_user_id_85e654_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_auth_tenant__e59187_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
